CREATE SCHEMA IF NOT EXISTS Biblioteca;

USE Biblioteca;

CREATE TABLE AUTORE (
	CODE_A	INT NOT NULL,
	NOME_A	VARCHAR(30) NOT NULL,
    COGNOME_A VARCHAR(15),
    DATAN 	DATE,
    LUOGON 	VARCHAR(30),
    
    PRIMARY KEY (CODE_A)
);

CREATE TABLE LIBRO (
	CODE_L		INT NOT NULL,
	TITOLO		VARCHAR(100) NOT NULL,
    ISBN		CHAR(11) NOT NULL,
    LINGUA		VARCHAR(15),
    ANNO		INT,
    NCOPIE		INT,
    
    UNIQUE (ISBN),
    UNIQUE (TITOLO),
    PRIMARY KEY (CODE_L)
);

CREATE TABLE SUCCURSALE (
	CODE_S		INT NOT NULL,
	NOME_S 		VARCHAR(50) NOT NULL,
    VIA_S		VARCHAR(30),
    CIVICO		VARCHAR(5), 
    CAP			INT,
    CITTA		VARCHAR(30),
    
    PRIMARY KEY(NOME_S),
    UNIQUE(NOME_S),
    UNIQUE(CODE_S)
);

CREATE TABLE UTENTE (
	NOME_U 		VARCHAR(15) NOT NULL,
    COGNOME_U 	VARCHAR(15) NOT NULL,
    INDIRIZZO_U	VARCHAR(30),
    TELEFONO	CHAR(10),
    MATRICOLA	CHAR(6) NOT NULL,
    
    PRIMARY KEY(MATRICOLA),
    UNIQUE(MATRICOLA)
);

CREATE TABLE PRESTITO (
	D_RITIRO		DATE NOT NULL,
    D_RICONSEGNA	DATE,
    LIBRO_P 		VARCHAR(100) NOT NULL,
    UTENTE_P		CHAR(6) NOT NULL,
    SUCCURSALE_P	VARCHAR(20) NOT NULL,
    
    FOREIGN KEY(UTENTE_P) REFERENCES UTENTE(MATRICOLA),
    FOREIGN KEY(SUCCURSALE_P) REFERENCES  SUCCURSALE(NOME_S),
    FOREIGN KEY(LIBRO_P) REFERENCES LIBRO(TITOLO)
);

CREATE TABLE HA_SCRITTO (
	NREL		INT,
	CODE_L_REL	INT NOT NULL,
    CODE_A_REL	INT NOT NULL,
    
    FOREIGN KEY(CODE_L_REL) REFERENCES LIBRO(CODE_L),
    FOREIGN KEY(CODE_A_REL) REFERENCES AUTORE(CODE_A)
);

LOAD DATA INFILE '/var/lib/mysql-files/Book.csv'
INTO TABLE LIBRO
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 0 ROWS;
    
LOAD DATA INFILE '/var/lib/mysql-files/Author.csv'
INTO TABLE AUTORE
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 0 ROWS;

LOAD DATA INFILE '/var/lib/mysql-files/Book_Authors.csv'
INTO TABLE HA_SCRITTO
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 0 ROWS;

LOAD DATA INFILE '/var/lib/mysql-files/Library_Branch.csv'
INTO TABLE SUCCURSALE
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 0 ROWS;

ALTER TABLE SUCCURSALE
	ADD COLUMN INDIRIZZO_S VARCHAR(100);
    
ALTER TABLE LIBRO
	ADD COLUMN AUTORE_L VARCHAR(1000);
    
SET SQL_SAFE_UPDATES = 0;

UPDATE SUCCURSALE SET INDIRIZZO_S = CONCAT_WS(' ',VIA_S,CIVICO,CAP,CITTA);
ALTER TABLE SUCCURSALE
	DROP COLUMN VIA_S,
    DROP COLUMN CIVICO,
    DROP COLUMN CAP,
    DROP COLUMN CITTA;
    
UPDATE AUTORE SET NOME_A = CONCAT_WS(' ',NOME_A,COGNOME_A);
ALTER TABLE AUTORE
	DROP COLUMN COGNOME_A;
       
SET SQL_SAFE_UPDATES = 1;    

INSERT INTO UTENTE
	VALUES('Marco', 'Bianchi', 'Via Bologna 27', '3462855217', '260284');
INSERT INTO UTENTE
	VALUES('Mario', 'Rossi', 'Via Verga 27', '3462855328', '260285');
INSERT INTO UTENTE
	VALUES('Giorgio', 'Miotto', 'Viale Cavour 29', '3462324217', '260286');
INSERT INTO UTENTE
	VALUES('Stefano', 'Bertelli', 'Via Argenta 34/B', '3213455217', '260287');
INSERT INTO UTENTE
	VALUES('Francesco', 'Contenti', 'Corso Giovecca 2', '3462857539', '260288');
INSERT INTO UTENTE
	VALUES('Nicola', 'Fergnani', 'Via Palmirano 45', '3463966328', '260289');
    
INSERT INTO PRESTITO
	VALUES('2022-05-01', '2022-05-31', 'Thief of Hearts', '260284', 'Architettura');
INSERT INTO PRESTITO
	VALUES('2022-06-15', '2022-07-15', 'Death Defying Acts', '260286', 'Ingegneria');
INSERT INTO PRESTITO
	VALUES('2022-01-06', '2022-02-23', 'Heroine', '260287', 'Giurisprudenza');
INSERT INTO PRESTITO
	VALUES('2020-01-06', '2020-02-23', 'Dead Man Walking', '260287', 'Giurisprudenza');
INSERT INTO PRESTITO
	VALUES('2021-01-06', '2021-02-23', 'Attack of the 50 Foot Woman', '260287', 'Giurisprudenza');
	